"""
    DM.API Account

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup

NAME = "dm-api-account"
VERSION = "v1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
  "structlog",
  "allure-pytest",
]

setup(
    name='dm_api_account',
    version='0.0.1',
    description="DM.API Account",
    author="lezov",
    author_email='-',
    url="https://github.com/allezov/openapi-templates.git",
    install_requires=REQUIRES,
    packages=['dm_api_account'],
)
# from distutils.core import setup
#
# REQUIRES = [
#     'records',
#     'allure-pytest',
#     'structlog',
#     'requests',
#     'pydantic'
# ]
#
# setup(
#     name='dm_api_account_clients',
#     version='0.0.5',
#     packages=['dm_api_account'],
#     url='https://github.com/allezov/dm_api_account.git',
#     license='Apache-2.0 license',
#     author='lezov',
#     author_email='-',
#     install_requires=REQUIRES,
#     description='dm_api_account_clients'
# )
